In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.3


In [4]:
# ndarray

In [5]:
arr = np.array(25)
print(arr)

25


In [6]:
print(arr.ndim)

0


In [7]:
arr1 = np.array([1,2,3,4,5])
print(arr)

25


In [8]:
print(arr1.ndim)

1


In [9]:
arr2 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
print(arr.ndim)

0


In [11]:
arr3 = np.array([ [ [1,2,3,4,5] , [6,7,8,9,10] ], [[11,12,13,14,15] , [16,17,18,19,20] ] ])
print(arr3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [12]:
print(arr3.ndim)

3


In [13]:
arr8 = np.array([1,2,3,4,5] , ndmin=8)
print(arr8)

[[[[[[[[1 2 3 4 5]]]]]]]]


In [14]:
print(arr.ndim)

0


In [15]:
print(arr1)
print(arr1[0])
print(arr1[3])
print(arr1[-2])

[1 2 3 4 5]
1
4
4


In [16]:
print(arr2)
print(arr2[0,2])
print(arr2[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
10


In [17]:
print(arr3)
print(arr3[0,1,1])
print(arr3[1,1,2])
print(arr3[1,0,3])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
7
18
14


In [18]:
# start : end : step
print(arr1)
print(arr1[1:4])
print(arr1[1:])
print(arr1[:4])
print(arr1[-3:-1])

[1 2 3 4 5]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[3 4]


In [19]:
print(arr1[1:4:1])
print(arr1[0:4:2])

[2 3 4]
[1 3]


In [20]:
print(arr1[::])

[1 2 3 4 5]


In [21]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(arr2[0:2 , 2:4 ])

[[3 4]
 [8 9]]


In [23]:
print(arr2[0:2 , 4:5 ])

[[ 5]
 [10]]


In [24]:
new = np.array([1,2,3,4,5])
print(new)

[1 2 3 4 5]


In [25]:
copy = new.copy()
view = new.view()
print(copy)
print(view)

[1 2 3 4 5]
[1 2 3 4 5]


In [26]:
new[0] = 45
print(copy)
print(view)

[1 2 3 4 5]
[45  2  3  4  5]


In [27]:
print(copy.base)
print(view.base)

None
[45  2  3  4  5]


In [28]:
print(arr1.shape)

(5,)


In [29]:
print(arr2.shape)

(2, 5)


In [30]:
print(arr3.shape)

(2, 2, 5)


In [31]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10,11, 12])
arr2d = arr1d.reshape(4,3)
arr3d = arr1d.reshape(2,2,3)
print(arr1d)
print("--------------")
print(arr2d)
print("--------------")
print(arr3d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
for x in arr1:
    print(x)

1
2
3
4
5


In [33]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [34]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [35]:
for x in np.nditer(arr1):
    print(x)

1
2
3
4
5


In [36]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [37]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [38]:
print(arr2[0:2 , 2:4 ])

[[3 4]
 [8 9]]


In [39]:
for x in np.nditer(arr2[0:2 , 2:4 ]):
    print(x)

3
4
8
9


In [40]:
for index, x in np.ndenumerate(arr2):
    print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [41]:
for index, x in np.ndenumerate(arr2[0:2 , 2:4 ]):
    print(index, x)

(0, 0) 3
(0, 1) 4
(1, 0) 8
(1, 1) 9


In [42]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
ar = np.concatenate((ar1 , ar2))
print(ar)

[1 2 3 4 5 6]


In [44]:
ar21 = np.array([[1,2],[3,4]])
ar22 = np.array([[5,6],[7,8]])
ar1 = np.concatenate((ar21 , ar22), axis=1)
ar0 = np.concatenate((ar21 , ar22), axis=0)
print(ar1)
print("--------------")
print(ar0)

[[1 2 5 6]
 [3 4 7 8]]
--------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
arrstack = np.stack((ar21 , ar22), axis=1)
print(arrstack)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [46]:
arrhstack = np.hstack((ar21 , ar22))
print(arrhstack)

[[1 2 5 6]
 [3 4 7 8]]


In [47]:
arrvstack = np.vstack((ar21 , ar22))
print(arrvstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
arrdstack = np.dstack((ar21 , ar22))
print(arrdstack)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [49]:
arrstack = np.stack((ar21 , ar22), axis=0)
print(arrstack)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
arr = np.array([2,5,8,9,6,4,58,65,45,58,95,68])
arr

array([ 2,  5,  8,  9,  6,  4, 58, 65, 45, 58, 95, 68])

In [51]:
print(arr)

[ 2  5  8  9  6  4 58 65 45 58 95 68]


In [52]:
split_array = np.array_split(arr , 5)
print(split_array)

[array([2, 5, 8]), array([9, 6, 4]), array([58, 65]), array([45, 58]), array([95, 68])]


In [53]:
split_array = np.array_split(arr , 10)
print(split_array)

[array([2, 5]), array([8, 9]), array([6]), array([4]), array([58]), array([65]), array([45]), array([58]), array([95]), array([68])]


In [54]:
split_array = np.array_split(arr , 15)
print(split_array)

[array([2]), array([5]), array([8]), array([9]), array([6]), array([4]), array([58]), array([65]), array([45]), array([58]), array([95]), array([68]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [56]:
arr2 = np.array([[ 2,  5],  [8,  9],  [6,  4], [58, 65], [45, 58], [95, 68 ]])
print(arr2)

[[ 2  5]
 [ 8  9]
 [ 6  4]
 [58 65]
 [45 58]
 [95 68]]


In [57]:
split_array = np.array_split(arr2 , 3)
print(split_array)

[array([[2, 5],
       [8, 9]]), array([[ 6,  4],
       [58, 65]]), array([[45, 58],
       [95, 68]])]


In [58]:
split_array = np.array_split(arr2 , 4)
print(split_array)

[array([[2, 5],
       [8, 9]]), array([[ 6,  4],
       [58, 65]]), array([[45, 58]]), array([[95, 68]])]


In [67]:
print(split_array[0][0,0])

2


In [59]:
arr = np.array([2,5,8,9,6,4,58,65,45,58,95,68])
arr

array([ 2,  5,  8,  9,  6,  4, 58, 65, 45, 58, 95, 68])

In [62]:
z = np.where(arr == 58)
print(z)

(array([6, 9]),)


In [61]:
even = np.where(arr%2 == 0 )
print(even)

(array([ 0,  2,  4,  5,  6,  9, 11]),)


In [68]:
arr[even]

array([ 2,  8,  6,  4, 58, 58, 68])

In [63]:
z = np.where(arr == 158)
print(z)

(array([], dtype=int64),)


In [70]:
arr = np.array([2,5,8,9,6,4,58,65,45,58,95,68, 85])

for x in arr:
    if '8' in str(x):
        print(x)

8
58
58
68
85


In [71]:
print(np.sort(arr))

[ 2  4  5  6  8  9 45 58 58 65 68 85 95]
