In [3]:
# pip install numpy

In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.3.3


In [7]:
# ndarray

In [15]:
arr = np.array(25)
print(arr)

25


In [16]:
print(arr.ndim)

0


In [28]:
arr1 = np.array([1,2,3,4,5])
print(arr)

[[[[[[[[1 2 3 4 5]]]]]]]]


In [29]:
print(arr1.ndim)

1


In [43]:
arr2 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
print(arr.ndim)

8


In [50]:
arr3 = np.array([ [ [1,2,3,4,5] , [6,7,8,9,10] ], [[11,12,13,14,15] , [16,17,18,19,20] ] ])
print(arr3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [51]:
print(arr3.ndim)

3


In [34]:
arr8 = np.array([1,2,3,4,5] , ndmin=8)
print(arr8)

[[[[[[[[1 2 3 4 5]]]]]]]]


In [35]:
print(arr.ndim)

8


In [39]:
print(arr1)
print(arr1[0])
print(arr1[3])
print(arr1[-2])

[1 2 3 4 5]
1
4
4


In [46]:
print(arr2)
print(arr2[0,2])
print(arr2[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
10


In [54]:
print(arr3)
print(arr3[0,1,1])
print(arr3[1,1,2])
print(arr3[1,0,3])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
7
18
14


In [60]:
print(arr1)
print(arr1[1:4])
print(arr1[1:])
print(arr1[:4])
print(arr1[-3:-1])

[1 2 3 4 5]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[3 4]
[1 2 3 4]
[1 3]


In [62]:
print(arr1[1:4:1])
print(arr1[0:4:2])

[2 3 4]
[1 3]


In [63]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [67]:
print(arr2[0:2 , 2:4 ])

[[3 4]
 [8 9]]


In [70]:
print(arr2[0:2 , 4:5 ])

[[ 5]
 [10]]


In [71]:
new = np.array([1,2,3,4,5])
print(new)

[1 2 3 4 5]


In [72]:
copy = new.copy()
view = new.view()
print(copy)
print(view)

[1 2 3 4 5]
[1 2 3 4 5]


In [73]:
new[0] = 45
print(copy)
print(view)

[1 2 3 4 5]
[45  2  3  4  5]


In [74]:
print(copy.base)
print(view.base)

None
[45  2  3  4  5]


In [75]:
print(arr1.shape)

(5,)


In [76]:
print(arr2.shape)

(2, 5)


In [77]:
print(arr3.shape)

(2, 2, 5)


In [84]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10,11, 12])
arr2d = arr1d.reshape(4,3)
arr3d = arr1d.reshape(2,2,3)
print(arr1d)
print("--------------")
print(arr2d)
print("--------------")
print(arr3d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [85]:
for x in arr1:
    print(x)

1
2
3
4
5


In [87]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [88]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [90]:
for x in np.nditer(arr1):
    print(x)

1
2
3
4
5


In [91]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [92]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [93]:
print(arr2[0:2 , 2:4 ])

[[3 4]
 [8 9]]


In [94]:
for x in np.nditer(arr2[0:2 , 2:4 ]):
    print(x)

3
4
8
9


In [95]:
for index, x in np.ndenumerate(arr2):
    print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [96]:
for index, x in np.ndenumerate(arr2[0:2 , 2:4 ]):
    print(index, x)

(0, 0) 3
(0, 1) 4
(1, 0) 8
(1, 1) 9


In [97]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [102]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
ar = np.concatenate((ar1 , ar2))
print(ar)

[1 2 3 4 5 6]


In [106]:
ar21 = np.array([[1,2],[3,4]])
ar22 = np.array([[5,6],[7,8]])
ar1 = np.concatenate((ar21 , ar22), axis=1)
ar0 = np.concatenate((ar21 , ar22), axis=0)
print(ar1)
print("--------------")
print(ar0)

[[1 2 5 6]
 [3 4 7 8]]
--------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [110]:
arrstack = np.stack((ar21 , ar22), axis=1)
print(arrstack)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [112]:
arrhstack = np.hstack((ar21 , ar22))
print(arrhstack)

[[1 2 5 6]
 [3 4 7 8]]


In [113]:
arrvstack = np.vstack((ar21 , ar22))
print(arrvstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [114]:
arrdstack = np.dstack((ar21 , ar22))
print(arrdstack)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [116]:
arrstack = np.stack((ar21 , ar22), axis=0)
print(arrstack)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
